CREATE TABLE IF NOT EXISTS emby (
  tg BIGINT PRIMARY KEY,
  iv INT NOT NULL DEFAULT 0,
  lv VARCHAR(8) NOT NULL DEFAULT 'd',
  embyid VARCHAR(128) DEFAULT '',
  name VARCHAR(255) DEFAULT '',
  free INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
